Repository designsystemsinternational/mechanic, pull requests merged in 2021-08, with the labels that each got.

#51 Image param
  packages/dsi-logo-maker/functions/textAndImageCanvas/index.js
  packages/dsi-logo-maker/functions/textAndImageSVG/index.js
  packages/dsi-logo-maker/utils/blocks-canvas.js
  packages/dsi-logo-maker/utils/blocks-components.js
  packages/mechanic-ui-components/app/index.css
  packages/mechanic-ui-components/app/index.js
  packages/mechanic-ui-components/src/ParamInput.js
  packages/mechanic-ui-components/src/buttons/Button.module.css
  packages/mechanic-ui-components/src/buttons/Toggle.module.css
  packages/mechanic-ui-components/src/index.js
  packages/mechanic-ui-components/src/input/ImageInput.js
  packages/mechanic-ui-components/src/input/ImageInput.module.css
  packages/mechanic-ui-components/src/input/NumberInput.module.css
  packages/mechanic-ui-components/src/variables.css
  packages/mechanic/app/pages/Function.js
  packages/mechanic/app/pages/utils/useValues.js
  packages/mechanic/src/mechanic-validation.js
Labels: beta nice to have, mechanic ui

#52 Image param release
  CHANGELOG.md
  lerna.json
  packages/create-mechanic/package.json
  packages/dsi-logo-maker/CHANGELOG.md
  packages/dsi-logo-maker/package.json
  packages/mechanic-cli/package.json
  packages/mechanic-engine-canvas/package.json
  packages/mechanic-engine-p5/package.json
  packages/mechanic-engine-react/package.json
  packages/mechanic-engine-svg/package.json
  packages/mechanic-ui-components/CHANGELOG.md
  packages/mechanic-ui-components/package-lock.json
  packages/mechanic-ui-components/package.json
  packages/mechanic-utils/package.json
  packages/mechanic/CHANGELOG.md
  packages/mechanic/package.json
Labels: changelog, release

#55 Refactor and language review in create-mechanic
  CHANGELOG.md
  packages/create-mechanic/CHANGELOG.md
  packages/create-mechanic/function-blank/dependencies.json
  packages/create-mechanic/function-blank/index.js
  packages/create-mechanic/index.js
  packages/create-mechanic/new-function.js
  packages/create-mechanic/new-project.js
  packages/create-mechanic/package.json
  packages/create-mechanic/script-content.js
  packages/mechanic-cli/CHANGELOG.md
  packages/mechanic-cli/commands/new.js
  packages/mechanic-utils/CHANGELOG.md
  packages/mechanic-utils/index.js
Labels: create-mechanic

#64 Update issue templates
  .github/ISSUE_TEMPLATE/---bug-report.md
  .github/ISSUE_TEMPLATE/---feature-request.md
Labels: release

#65 Design function bundle refactor
  CHANGELOG.md
  package-lock.json
  packages/mechanic/CHANGELOG.md
  packages/mechanic/app/function-loader.cjs
  packages/mechanic/app/functions.js
  packages/mechanic/app/pages/Function.js
  packages/mechanic/app/webpackConfigGenerator.cjs
  packages/mechanic/package.json
  packages/mechanic/src/commands/build.cjs
  packages/mechanic/src/commands/dev.cjs
  packages/mechanic/src/commands/serve.cjs
  packages/mechanic/src/commands/utils.cjs
  packages/mechanic/src/function-set-up.js
Labels: enhancement

#70 Iframe wrapping support
  CHANGELOG.md
  lerna.json
  packages/cli/package.json
  packages/core/CHANGELOG.md
  packages/core/app/index.js
  packages/core/app/webpackConfigGenerator.cjs
  packages/core/package.json
  packages/core/src/commands/build.cjs
  packages/create/new-function.js
  packages/create/package.json
  packages/dsi-logo-maker/package.json
  packages/engine-canvas/package.json
  packages/engine-p5/package.json
  packages/engine-react/package.json
  packages/engine-svg/package.json
  packages/fonts/package.json
  packages/ui-components/package.json
  packages/utils/package.json
Labels: documentation, beta

#72 [Docs] Adds list of available params and settings
  doc/doc.md
  packages/core/src/mechanic-validation.js
Labels: documentation, beta
